"""add key_hint to provider_credentials

Revision ID: 13a604fc1c98
Revises: 5152a4e85862
Create Date: 2026-08-07 07:34:06.901578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '13a604fc1c98'
down_revision: Union[str, None] = '5152a4e85862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows predate key_hint; backfill with a placeholder so NOT NULL can apply cleanly.
    # Real values land next time each credential is re-saved via PUT /provider-credentials/{provider}.
    op.add_column(
        'provider_credentials',
        sa.Column('key_hint', sa.String(length=4), nullable=False, server_default='????'),
    )
    op.alter_column('provider_credentials', 'key_hint', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_credentials', 'key_hint')
    # ### end Alembic commands ###
