"""add provider credentials

Revision ID: 5152a4e85862
Revises: ec903e8957e9
Create Date: 2026-08-07 04:29:30.433752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5152a4e85862'
down_revision: Union[str, None] = 'ec903e8957e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('encrypted_api_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'provider', name='uq_provider_credentials_owner_provider')
    )
    op.create_index(op.f('ix_provider_credentials_owner_id'), 'provider_credentials', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_credentials_owner_id'), table_name='provider_credentials')
    op.drop_table('provider_credentials')
    # ### end Alembic commands ###
