"""add citations to messages

Revision ID: bb08f6e387fa
Revises: 13a604fc1c98
Create Date: 2026-08-07 07:55:44.402582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bb08f6e387fa'
down_revision: Union[str, None] = '13a604fc1c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing messages predate citation snapshots; backfill with an empty list so NOT NULL
    # applies cleanly. Old messages just show no sources, which matches what already happened.
    op.add_column(
        'messages',
        sa.Column('citations', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.alter_column('messages', 'citations', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'citations')
    # ### end Alembic commands ###
